# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bank_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  bank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_db
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_password
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/master.xml
      JWT_SECRET: your-strong-jwt-secret-key-32-chars-long
      ENCRYPTION_SECRET_KEY: your-32-char-secret-for-aes-encryption
    ports:
      - "8080:8080"
    networks:
      - bank_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge
