#
# application.yml — главный конфигурационный файл Spring Boot.

# Основные настройки приложения
spring:
  application:
    name: bank-card-system

  # Настройки базы данных (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: bank_user
    password: strongpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Настройки JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate # Liquibase управляет схемой
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Настройки Liquibase
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
    default-schema: public

  # Настройки безопасности
  security:
    user:
      name: admin
      password: adminpass
      roles: ADMIN

# Настройки JWT
jwt:
  secret: your-strong-jwt-secret-key-32-chars-long # Генерируйте случайный ключ
  expiration-ms: 86400000 # 24 часа

# Настройки шифрования карт
encryption:
  secret-key: your-32-char-secret-for-aes-encryption # Должен быть ровно 32 символа

# Настройки Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none

# Настройки логирования
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.bank: DEBUG

# Настройки сервера
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
